export const GET_TRANSACTIONS_STARTED = 'GET_TRANSACTIONS_STARTED';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

export const POST_BALANCE_STARTED = 'POST_BALANCE_STARTED';
export const POST_BALANCE_SUCCESS = 'POST_BALANCE_SUCCESS';
export const POST_BALANCE_FAILURE = 'POST_BALANCE_FAILURE';

export const GET_REAL_CATEGORIES_STARTED = 'GET_REAL_CATEGORIES_STARTED';
export const GET_REAL_CATEGORIES_SUCCESS = 'GET_REAL_CATEGORIES_SUCCESS';
export const GET_REAL_CATEGORIES_FAILURE = 'GET_REAL_CATEGORIES_FAILURE';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const LOGOUT = 'LOGOUT';

export const GET_CATEGORIES_STARTED = 'GET_CATEGORIES_STARTED';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_COSTS_STARTED = 'GET_COSTS_STARTED';
export const GET_COSTS_SUCCESS = 'GET_COSTS_SUCCESS';
export const GET_COSTS_ERROR = 'GET_COSTS_ERROR';

export const DELETE_COST_STARTED = 'DELETE_COST_STARTED';
export const DELETE_COST_SUCCESS = 'DELETE_COST_SUCCESS';
export const DELETE_COST_ERROR = 'DELETE_COST_ERROR';
export const SET_ALERT_ON = 'SET_ALERT';
export const SET_ALERT_OFF = 'SET_ALERT_OFF';

export const POST_COSTS_STARTED = 'POST_COSTS_STARTED';
export const POST_COSTS_SUCCESS = 'POST_COSTS_SUCCESS';
export const POST_COSTS_FAILURE = 'POST_COSTS_FAILURE';
export const DO_INCREMENT = 'DO_INCREMENT';
export const DO_DECREMENT = 'DO_DECREMENT';
