export const GET_TRANSACTIONS_STARTED = 'GET_TRANSACTIONS_STARTED';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';
export const POST_BALANCE_STARTED = 'POST_BALANCE_STARTED';
export const POST_BALANCE_SUCCESS = 'POST_BALANCE_SUCCESS';
export const POST_BALANCE_FAILURE = 'POST_BALANCE_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const LOGOUT = 'LOGOUT';
