export const GET_TRANSACTIONS_STARTED = 'GET_TRANSACTIONS_STARTED';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

export const POST_BALANCE_STARTED = 'POST_BALANCE_STARTED';
export const POST_BALANCE_SUCCESS = 'POST_BALANCE_SUCCESS';
export const POST_BALANCE_FAILURE = 'POST_BALANCE_FAILURE';

export const GET_CATEGORIES_STARTED = 'GET_CATEGORIES_STARTED';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const SET_ALERT_ON = 'SET_ALERT';
export const SET_ALERT_OFF = 'SET_ALERT_OFF';
